# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#>.
@prefix nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>.

<http://purl.org/NET/cpan-uri/dist/P5U/project>
	:perl_version_from  _:main;
	:version_from       _:main;
	:readme_from        _:main;
	:install_script     _:script;
	:requires           "App::Cmd";
	:requires           "autodie";
	:requires           "Class::Load";
	:requires           "File::HomeDir";
	:requires           "File::pushd";
	:requires           "JSON 2.00";
	:requires           "LWP::Simple";
	:requires           "Module::Info";
	:requires           "Module::Manifest";
	:requires           "Moo 1.000000";
	:requires           "namespace::clean 0.19";
	:requires           "Object::AUTHORITY";
	:requires           "Path::Class";
	:requires           "Path::Class::Rule";
	:requires           "PerlX::Maybe";
	:requires           "Scalar::Does 0.004";
	:requires           "Test::Pod";
	:test_requires      "Test::More 0.61".

_:main nfo:fileName "lib/P5U.pm".
_:script nfo:fileName "bin/p5u".

